### ISSUE TITLE
[Recipe] Convert any value to string

### ISSUE THREAD

**Issue by jcubic** [schemedoc/cookbook#8]
## Problem
You need a function that will convert any value to a string

## Solution
```scheme
(define-values (displayed written)
  (let ((repr (lambda (fn)
                (lambda (object)
                  (call-with-port (open-output-string)
                                  (lambda (port)
                                    (fn object port)
                                    (get-output-string port)))))))
    (values (repr display) (repr write))))
```
Credit @jcubic

### SRFI
The functions `displayed` and `written` are also defined by SRFI 166.

## Usage
```scheme
(define (print x)
  (display x)
  (newline))

(print (written #\x))
;; ==> #\x
(print (written "foo"))
;; ==> "foo"
(print (written '(1 2 3)))
;; ==> (1 2 3)
```

**Comment by lassik** [comment]
This procedure is sometimes called `written` as a reminder that it uses `write` internally. `(written '(1 2 3))` is kind of idiomatic in English, since the result is a written version of `(1 2 3)`.

**Comment by lassik** [comment]
`(displayed "foo")` would be the same, but uses `display` instead of `write` internally.

**Comment by jcubic** [comment]
`repr` is the function from Python, this is how I've added this function to my Scheme interpreter, internally it's called toString. The function accepts a second argument that indicates if it should do what write or display does.

**Comment by lassik** [comment]
Yes, Python uses `repr` and `str`. The names `written` and `displayed` are from [SRFI 166](https://srfi.schemers.org/srfi-166/srfi-166.html).

**Comment by jcubic** [comment]
There are a lot of solutions in SRFI documents. I've only seen a fraction of them, that's why I'm implementing things that are already been implemented. The solution can mention that this is in SRFI 166 and I can create a higher-order function that will define both functions.

**Comment by APIPLM** [comment]
As I played with `format` in chicken 5.2.0,by in the module `,m srfi-28`, then I intended to have an invalid escape sequence as the input like this `(format "Hello, ~12" "World!")`. The error is that 
```
Error: (sprintf) illegal format-string character: #\1
 Call history:

        <syntax>          (format "Hello, ~12" "World!")
        <eval>    (format "Hello, ~12" "World!")        <--
```
The question is that symbol `sprintf` have not been in the current environment yet as I typed `sprintf`, it is needed to `import (chicken format)`. Sound like the wrong is related to the symbol  `sprintf` . But as checked it. the error information is
`Error: unbound variable: sprintf`
As having valid escape sequence  `(format "Hello, ~a" "World!")`, it works.
There is a little bit confusions, which is that without `import (chicken format)`, the symbol  `sprintf` is not there, how can `(format "Hello, ~a" "World!")`  still works, and the invalid escape sequence as the input, report the information of the symbol `sprintf` is not the current environment . I guest that most is related to the implementation.

**Comment by jcubic** [comment]
I think that `sprintf` is C function, not Scheme and the error came from Chiken implementation that uses sprintf. But this is just a guess.

**Comment by APIPLM** [comment]
@jcubic  Yes. As I investigated from [the source ](https://code.call-cc.org/releases/5.2.0/chicken-5.2.0.tar.gz). The module `format` is happening the file `.\chicken-5.2.0\extras.scm`  with `register-feature! 'srfi-28`, which is not the implementation in the specification of srfi-28.

**Comment by APIPLM** [comment]
And as well when `import srfi-28`,there is not any separate .so file loaded.

**Comment by lassik** [comment]
@jcubic Chicken has a [Scheme procedure named `sprintf`](http://api.call-cc.org/5/doc/chicken/format/sprintf). It has the same name as the standard C function, but it's a different one.

@APIPLM As you noticed, an implementation of SRFI 28 is included with Chicken, so `(import (srfi 28))` and `(format "~a" 'foo)` will work. The error `illegal format-string character: #\1` means what is says: [SRFI 28](https://srfi.schemers.org/srfi-28/srfi-28.html) is very simple and does not support `~1`. It only supports `~a ~s ~% ~~`.

Even though you are calling `format`, the error message says `sprintf`, because in Chicken, `format` is implemented by calling `sprintf` internally.

**Comment by lassik** [comment]
Basically it's implemented like this:

```Scheme
(define-library (srfi 28)
  (export format)
  (import (rename (chicken format) (sprintf format))))
```

They are actually using Chicken's native module system instead of the R7RS `define-library`, but the idea is the same. The implementation of `format` is in `extras.scm` in the `chicken-core` repo.

**Comment by lassik** [comment]
This recipe is now at https://cookbook.scheme.org/convert-any-value-to-string/

**Comment by APIPLM** [comment]
Thanks. But when I looked back again, after` ,m srfi-28 ` the user mostly thought that it is in interpreted module. And all of the symbols are available as he/she switches the "current module" . In our case, it all symbols `format `, `sprintf `, `sprintf` and `printf` should be in `srfi-28 ` module. But the fact is that only `format ` is there, and other symbols are consider internally. And also I check `getter-with-setter ` in srfi-17 in Chicken. What I find out is that  in REPL , get into the module  by ` ,m srfi-17`, and then `getter-with-setter` is not there. And as check in `csi` without switching to the module `srfi-17`, it is there.
Somehow, I feel like that these SRFIs like bundled implantation SRFIs  for the top level module  in Chicken,   there is not any meaning for user to switch to these modules, even top level module have this ability in hand.

One more point is what I found is the new version for this receipt. See the below code block.
```
(define ->string 
  (lambda (x)
    (cond [(string? x) x]
	  [(symbol? x) (symbol->string x)]
	  [(char? x) (string x)]
	  [(number? x) (##sys#number->string x)]
	  [else 
	   (let ([o (open-output-string)])
	     (display x o)
	     (get-output-string o) ) ] ) ) ) 
```

We did not think about immutable object like `char ` `number ` and `symbol ` , as also the name of procedure is better than ours .

**Comment by lassik** [comment]
Our recipe uses `display` and `write. Both of them can write numbers and symbols. In Scheme, `displayed` and `written` are more obvious names than `->string`, and `object->string` would be a more conventional name than Chicken's `->string`.

---

> all symbols `format `, `sprintf `, `sprintf` and `printf` should be in `srfi-28 ` module

Nope, [SRFI 28](https://srfi.schemers.org/srfi-28/srfi-28.html) only exports `format`. There's no mention of `printf` in the SRFI. `sprintf` is a Chicken procedure, not a SRFI 28 procedure.

> get into the module by ` ,m srfi-17`, and then `getter-with-setter` is not there

Congratulations, you have found a bug in Chicken :) `(srfi 17)` should export `getter-with-setter` and `setter`.

> And as check in `csi` without switching to the module `srfi-17`, it is there.

Chicken exports `getter-with-setter` from the `(chicken base)` library. It shows up in the REPL because the REPL imports `(chicken base)` by default.

> Somehow, I feel like that these SRFIs like bundled implantation SRFIs for the top level module in Chicken, there is not any meaning for user to switch to these modules, even top level module have this ability in hand.

Yes. It's only necessary to use `,m` to go into the SRFI modules if you are fixing bugs in that SRFI. If you only want to use a SRFI, `(import (srfi 28))` and `(import (srfi 17))` are the right thing to use.

**Comment by APIPLM** [comment]
The Chicken SRFI-28 is a native implementation, the user come into the module `,m srfi-28` can only see the exported symbol `format`, not  internal symbol 'sprintf' in the native implementation, I have not found the source file in the folder chicken-5.2.0 yet about exported symbol `format`, and also `getter-with-setter` in SRFI-17, where is the source file  `(import (chicken base))` by default import. It is in the `csi.scm` file?
Although we can check with the command `lsof ` the process of the csi, then `strings `the loaded `so `file to find out. I mean that is different for user to check it those. I rather have a environment to bundled those SRFIs with passed test case, then start to work. Basically meaning is that bundled implemented SRFIs with passed test cases is a start point. Not native implementation and register to SRFIs, this way it is difficulty for the user to contribute SRFIs. Then for the collaboration, SRFIs contribution is just in the document level , also it is without reasonable revision traceability.

**Comment by lassik** [comment]
SRFI 17 and 28 are built into Chicken. They don't have their own source files (or `.so` files) because they just re-export procedures from other libraries. Search for `srfi-17` and `srfi-28` in [`modules.scm`](https://code.call-cc.org/cgi-bin/gitweb.cgi?p=chicken-core.git;a=blob_plain;f=modules.scm;hb=HEAD) and you will find the definitions.

**Comment by lassik** [comment]
I reported the `srfi-17` bug (missing `setter` and `getter-with-setter`) and they will fix in the next release.

**Comment by APIPLM** [comment]
Yes. in the [module.scm ](https://code.call-cc.org/cgi-bin/gitweb.cgi?p=chicken-core.git;a=blob_plain;f=modules.scm;hb=HEAD)source file. it register the modules srfi-17 and srfi-28.
```
(##sys#register-primitive-module
 'srfi-17 '() (se-subset '(set!) ##sys#default-macro-environment))

(##sys#register-core-module
 'srfi-28 'extras '((format . chicken.format#format)))
```
For srfi-17, `setter ` and `getter-with-setter` was not registered, that is why we can not see them in REPL after `,m srfi-17` 
And for srfi-28, `format` was registered, then we can see it in REPL after `,m srfi-28` because it is an exported symbol.

All these symbols  `setter ` and  `getter-with-setter` in srfi-17 and `format` in srfi-28, the actual binary code is in `libchicken.so.11 ` file and are exported. But it is about those symbols was registered into which module. For our case, `format` was registered into the `srfi-28` module, then  after `,m srfi-17` in REPL, symbol `format `can be seen. `setter ` and `getter-with-setter`  were not registered, it like is in the default  `chicken base` module. Then we can see them in REPL without importing any module as REPL `imports (chicken base) ` by default.
It like `(import moduleABC)` quite equally load the corresponding `moduleABC.import.so` file if it has `moduleABC.import.so` file. And create the name moduleABC into the current running scheme system, then` ,m moduleABC` ,the exported symbols will be available in moduleABC. Let us say, `format`, it was registered into srfi-28, there is an alist ` (format . chicken.format#format) `in `(##sys#register-primitive-module  'srfi-17 '() (se-subset '(set!) ##sys#default-macro-environment))`, the first element of alist is `format `will be in srfi-28, the second element alist `format  `is the original module ` chicken.format`. so this like in the below.
```
#;srfi-28:3> format
#<procedure (chicken.format#format fmt-or-dst . args)>
```

Following the same logical, if we want to have only r5rs everin, it would be like
`,m r4rs-null  `    ;;only r4rs syntax
`(import r5rs) `   ;; create then name r5rs for r5rs ( is renamed scheme)  module with all exported symbols in `libchicken.so.11 ` file to be available in REPL. Sound like reasonable.:).

**Comment by lassik** [comment]
Yes.

Chicken already has an `r5rs` module. I'm not sure whether it's built-in, or comes from the `r7rs` egg.

**Comment by APIPLM** [comment]
In Chicken, the name r5rs of r5rs module is there. From toplevel script point view, it is hard to say the exported procedures in this module are built-in, or come from the `r7rs ` egg because some of exported procedures are built-in, then in the `r7rs `egg those exported procedures have a new definition ( a new implementation ), and also in `r7rs `egg  and `r5rs `egg  both of the implementations of those procedures are compatibility.  But most exported procedures are built-in. It like the binary code of one exported procedure is in the `libchicken.so.11` file, and there is a patch (binary code ) in `scheme.base.so `file as well. For instance, in Chicken the` list->vector `procedure has the definition in the `library.scm` file, it is build-in. in the `r7rs `egg, there is also a definition for it in `scheme.base.scm` file. See the below.
`,m r4rs-null`
`(import r7rs)`

```
#;r4rs-null:2> vector->list
#<procedure (scheme.base#vector->list g1044 . rvar)>
```
Both `(vector->list #("A" "B")) `and `(vector->list #("A" "B") 0 2)` work.

`,m r4rs-null`
`(import r5rs)`

```
#;r4rs-null:4> vector->list
#<procedure (scheme#vector->list v)>
```
Only `(vector->list #("A" "B")) ` work.

In the` r7rs.egg` file in the source files of `r7rs `egg , the scheme.r5rs module is in dependence list
